### ISSUE TITLE
Docker-compose version 2

### ISSUE THREAD

**Issue by SidMorad** [VincentDS/OpenStreetMap-Tileserver-DockerCompose#1]
Any plan for supporting docker-compose version 2 ?

I am trying to make this work in version 2 with following syntax:
```
version: '2'
services:
  start-data:
    image: busybox
    volumes:
      - /var/lib/start
  postgres-osm:
    image: openfirmware/postgres-osm
    restart: unless-stopped
  osm2pgsql:
    image: vincentds1/osm2pgsql
    links:
      - postgres-osm:pg
    volumes:
      - ~/osm:/osm
    volumes_from:
      - start-data
    command: /etc/start.sh
  shapefiles:
    image: vincentds1/shapefiles
  osm-bright:
    image: vincentds1/osm-bright
    volumes_from:
      - start-data
      - shapefiles
    links:
      - postgres-osm:pg
  tiles-data:
    image: busybox
    volumes:
      - /var/lib/tiles
  renderd:
    image: vincentds1/renderd
    volumes_from:
      - start-data
      - osm-bright
      - tiles-data
    ports:
      - "80:80"
    links:
      - postgres-osm:pg
    depends_on:
      - postgres-osm
    command: /etc/start.sh
    restart: unless-stopped
```
and I notice following log after `docker-compose up -d` command:
> docker_shapefiles_1 exited with code 0

and unlike version 1 following message is keep going for ever:
> renderd still waiting for osm2pgsql & osm-bright to complete..

I did search for the solution and I find following post helpful:
https://medium.com/@giorgioto/docker-compose-yml-from-v1-to-v2-3c0f8bb7a48e

and my first guest is the problem might be in volume sharing area, but so far I had no luck on testing different syntax.

Any suggestion for testing different syntax?
At the moment I don't know how to debug the issue, any guide on that also will be greatly appreciated.

Thanks for this repository! :+1:
